server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: companyModule
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/company/**
        - id: sectorModule
          uri: lb://SECTOR-SERVICE
          predicates:
            - Path=/sector/**
        - id: exchangeModule
          url: lb://EXCHANGE-SERVICE
          predicates:
            - Path=/exchange/**